# Generated by Django 5.2.4 on 2025-10-12 12:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('seat_capacity', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FareClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, help_text='Optional route code', max_length=16, null=True)),
                ('flight_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('regional', 'Regional'), ('longhaul', 'Long Haul')], default='domestic', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_routes', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_routes', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('landed', 'Landed')], default='scheduled', max_length=16)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('gate', models.CharField(blank=True, max_length=8, null=True)),
                ('terminal', models.CharField(blank=True, max_length=8, null=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.airline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.route')),
            ],
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('refundable', models.BooleanField(default=False)),
                ('baggage_allowance_kg', models.PositiveIntegerField(default=15)),
                ('seat_count', models.PositiveIntegerField(default=0)),
                ('fare_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules', to='flights.fareclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='flights.flight')),
            ],
            options={
                'indexes': [models.Index(fields=['flight', 'fare_class'], name='flights_far_flight__9d49b1_idx')],
                'unique_together': {('flight', 'fare_class')},
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination', 'flight_type'], name='flights_rou_origin__fe1c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination', 'flight_type')},
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time', 'status'], name='flights_fli_departu_91e77a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('airline', 'flight_number', 'departure_time')},
        ),
    ]
