# Generated by Django 5.2.4 on 2026-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
